<?php  if ( ! defined("BASEPATH")) exit("No direct script access allowed");
$config["useragent"] = "CodeIgniter";
$config["protocol"]  = "smtp";
$config["smtp_host"] ="smtp.gmail.com";
$config["smtp_user"] ="issabanihachim@gmail.com";
$config["smtp_pass"] ="Issa@Aly#1997";
$config["smtp_port"] ="587";
$config["smtp_timeout"] ="5";
$config["wordwrap"]  = "TRUE";
$config["wrapchars"]  = "76";
$config["mailtype"] ="html";
$config["charset"] ="UTF-8";
$config["validate"]  = "FALSE";
$config["priority"]  = "3";
$config["crlf"]  = "\r\n";
$config["newline"]="\r\n";
$config["bcc_batch_mode"] ="FALSE";
$config["bcc_batch_size"] ="200";
